### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by JGAntunes** [shelf-js/shelf#13]
This issue shouldn't probably be here but well... We desperately need a chat or some way of easily communicating. It's easy for me and @ricardofbarros to chat but it would be cool to find something good to include @pmvrmc too. Any ideas? Do you have telegram @pmvrmc? Or maybe IRC channel on freenode?

**Comment by pmvrmc** [comment]
Hmmm, I don't have a telegram account but I can create one...
Or what do you think about slack? I just created a team there and sent you invites.

If you prefer telegram I will create an account there ;)

**Comment by JGAntunes** [comment]
Awesome! Slack sounds cool. Closing it ;)
