### ISSUE TITLE
Default value for properties

### ISSUE THREAD

**Issue by pmvrmc** [shelf-js/shelf#5]
It would be interesting to allow default properties on objects to be stored on redis.

Something like this:

shelf.extend({
    name: 'model',
    props: {
      prop1: 'string',
      prop2: 'string', 
    },
    defaults: {
      prop2: 'value2'
    },
    keys: ['prop1']
});

**Comment by ricardofbarros** [comment]
Yeah, that is a great idea. 

We are temporarily stalled on this package's development, so any PR is welcome ;)

**Comment by pmvrmc** [comment]
Sure, I will work on it and submit a PR :)
